### ISSUE TITLE
Is there a way read and export macOS default keybinding before put files to `~/Library/KeyBindings/`?

### ISSUE THREAD

**Issue by suliveevil** [ttscoff/KeyBindings#17]

**Comment by suliveevil** [comment]
https://forum.keyboardmaestro.com/t/os-x-text-system-keybindings/4929

```shell
plutil -convert xml1 \
/System/Library/Frameworks/AppKit.framework/Resources/StandardKeyBinding.dict -o - | \
pl | grep -v noop: | ruby -pe'$_.gsub!(/[^ -~\n]/){"\\U%04x"%$&.ord}'
```

**Comment by hym3242** [comment]
Don't forget those symbols in AppKit, and those default key bindings not listed in StandardKeyBinding.dict like ctrl+q (quoted-insert, insert special symbols and literal bytes)
